### ISSUE TITLE
Update derelict-util

### ISSUE THREAD

**Issue by cwkx** [Extrawurst/DerelictImgui#2]
Hi, would it be possible to update derelict-util to `2.x.y` instead of `~>1.9.1` 
re: https://github.com/DerelictOrg/DerelictCL/issues/1 thanks

**Comment by extrawurst** [comment]
i guess. will look into it later today or tomorrow asap

**Comment by cwkx** [comment]
thanks so much

**Comment by extrawurst** [comment]
in the meantime you can fix it locally using a fork

**Comment by extrawurst** [comment]
v0.5.0 uses DerelictUtil "~>2.0.0" (see https://github.com/Extrawurst/DerelictImgui/commit/147a8b9c0b8d1e5ae4a7dfc221fd2226fc7b3d62)
