### ISSUE TITLE
enum ImGuiSelectableFlags_ has unnecessary name

### ISSUE THREAD

**Issue by MrSmith33** [Extrawurst/DerelictImgui#3]
In types.d `enum ImGuiSelectableFlags_` should not have a name

**Comment by extrawurst** [comment]
you are right. i will takle that once a new imgui release is out the door

**Comment by MrSmith33** [comment]
I have some things to ask:
- Will you add bindings for every function in imgui?
- Why choosing `igGetCursorScreenPos(ImVec2* pOut)` over `ImVec2 igGetCursorScreenPos()`
- I've done all bindings of functions in ImDrawList both for cimgui and for DerelictImgui, do you interested in pull request?
- Is it possible to directly bind to C++ dll now, as we have some support in D for it?

Btw, VS2013 solution for cimgui was very helpful!

**Comment by extrawurst** [comment]
1) IMHO every method in the ImGui namespace is there, if something is missing please create an issue and feel also free to create a PR for it
2) I have to recheck that, I cannot remember from the top of my head.
3) Please feel free to create PRs for both
4) Some day maybe, right now it is not stable enough and backward compatible enough.

**Comment by MrSmith33** [comment]
Will do PR soon.
2)

``` C
void igGetContentRegionMax(struct ImVec2* out);
void igGetContentRegionAvail(struct ImVec2* out);
void igGetWindowContentRegionMin(struct ImVec2* out);
void igGetWindowContentRegionMax(struct ImVec2* out);
void igGetWindowPos(struct ImVec2* out);
void igGetWindowSize(struct ImVec2* out);
void igGetCursorPos(struct ImVec2* pOut);
void igGetCursorStartPos(struct ImVec2* pOut);
void igGetCursorScreenPos(struct ImVec2* pOut);
void igGetItemRectMin(struct ImVec2* pOut);
void igGetItemRectMax(struct ImVec2* pOut);
void igGetItemRectSize(struct ImVec2* pOut);
void igCalcItemRectClosestPoint(struct ImVec2* pOut, const struct ImVec2 pos, bool on_edge, float outward);
void igCalcTextSize(struct ImVec2* pOut, const char* text, const char* text_end, bool hide_text_after_double_hash, float wrap_width);
void igGetMousePos(struct ImVec2* pOut);
void igGetMousePosOnOpeningCurrentPopup(ImVec2* pOut);
void igGetMouseDragDelta(struct ImVec2* pOut, int button, float lock_threshold);
```

Can be found with `ImVec2\* p?out` in cimgui.h
- Do you prefer CONST or const in cimgui?
  UPD: accidentaly replaced `#define CONST const` with `#define const const`, nvm.

**Comment by extrawurst** [comment]
Thanks for the PR - i will have a look after work.
regarding the methods: Thanks for listing them but I have to test why I did that, there was a reason. I should have documented this ;)

**Comment by extrawurst** [comment]
I had problems returning structs on the stack when writing the D-Bindings that was the reason for pOut pointer
